/* Generated By:JavaCC: Do not edit this line. miniCConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface miniCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TYPE = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int FOR = 13;
  /** RegularExpression Id. */
  int ID = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int ZERO = 18;
  /** RegularExpression Id. */
  int GPAR = 19;
  /** RegularExpression Id. */
  int DPAR = 20;
  /** RegularExpression Id. */
  int VIRGULE = 21;
  /** RegularExpression Id. */
  int GACC = 22;
  /** RegularExpression Id. */
  int DACC = 23;
  /** RegularExpression Id. */
  int POINTVIRGULE = 24;
  /** RegularExpression Id. */
  int AFFECT = 25;
  /** RegularExpression Id. */
  int EQ = 26;
  /** RegularExpression Id. */
  int LT = 27;
  /** RegularExpression Id. */
  int LTE = 28;
  /** RegularExpression Id. */
  int GT = 29;
  /** RegularExpression Id. */
  int GTE = 30;
  /** RegularExpression Id. */
  int NEQ = 31;
  /** RegularExpression Id. */
  int ADD = 32;
  /** RegularExpression Id. */
  int SUB = 33;
  /** RegularExpression Id. */
  int MUL = 34;
  /** RegularExpression Id. */
  int DIV = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<TYPE>",
    "\"if\"",
    "\"else\"",
    "\"int\"",
    "\"float\"",
    "\"while\"",
    "\"for\"",
    "<ID>",
    "<NUMBER>",
    "<LETTER>",
    "<DIGIT>",
    "\"0\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"==\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
